### ISSUE TITLE
%player_biome% failure on Paper 1.21.10 (and 1.21.9)

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/Player-Expansion#98]
```
> version
[22:16:53 INFO]: This server is running Paper version 1.21.10-69-main@610f1d2 (2025-10-12T01:31:53Z) (Implementing API version 1.21.10-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.10-64-fba780d (MC: 1.21.10)
> papi info player
[22:16:56 INFO]: Placeholder expansion info for: player
Status: Registered
Author: clip
Version: 2.0.8

> papi parse SlimeDog %player_biome%
[22:17:01 INFO]: CraftBiome{holder=Reference{ResourceKey[minecraft:worldgen/biome / minecraft:snowy_plains]=net.minecraft.world.level.biome.Biome@1a10d389}}

> papi parse SlimeDog %player_biome_capitalized%
[22:19:44 INFO]: Craftbiome{holder=reference{resourcekey[minecraft:worldgen/biome / minecraft:snowy Plains]=net.minecraft.world.level.biome.biome@1a10d389}}
```

should return SNOWY_PLAINS
it did, in previous Paper versions

**Comment by CloudeLecaw** [comment]
im.also having it since we switched to 1.21.9/10

by the way - it happens with all biomes the placeholder should try to parse.

so might the expansion needs an update

<img width="1321" height="335" alt="Image" src="https://github.com/user-attachments/assets/11bc0281-840b-4a73-bb5a-f4c6c5287188" />

**Comment by PiggyPiglet** [comment]
Should be fixed #c264f9f, they changed Biome from an enum to interface in 1.21.3 and that cooked it. Probably won't work forever as 1.21.3 >= now relies on #name() which is deprecated, but will fix it properly when I get more time

**Comment by SlimeDog** [comment]
Excellent. Please publish it.

**Comment by CloudeLecaw** [comment]
in current 2.0.9 the issue still seems to exist, even if it was mentioned to be sloved with this version :3

<img width="1762" height="694" alt="Image" src="https://github.com/user-attachments/assets/cbcba8f5-df04-4583-a769-ccdf6755a621" />

![Image](https://github.com/user-attachments/assets/9e15820f-cb93-4cc6-b602-0c2d7198dc2b)

![Image](https://github.com/user-attachments/assets/c19c469c-b029-415a-96ec-711ff3c62e35)

on our liveserver i disabled the seeing biom for now from the tablist. on our testserver its still active so i could look at it for a return if its fixed :-)

**Comment by PiggyPiglet** [comment]
@CloudeLecaw I can't reproduce, your tab plugin must be caching placeholder results or something, but running your paper build with the latest version of papi and player expansion, /papi parse me %player_biome% returns the correct result

**Comment by SlimeDog** [comment]
Thanks. Confirmed Player 2.0.9 correctly parses %player_biome% on Paper 1.21.10-91.

**Comment by CloudeLecaw** [comment]
> Thanks. Confirmed Player 2.0.9 correctly parses %player_biome% on Paper 1.21.10-91.

i can confirm its parsed correct now. So its CMI that parses it wrongly now.
i allready created a ticket on their github

https://github.com/Zrips/CMI/issues/9927
